## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.

In [ ]:
import numpy as np
import pandas as pd

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [2]:
np.version.version

'1.18.1'

2. Crear un arreglo 1D con enteros positivos aleatorios

In [3]:
arregloInt = np.random.randint(low=0, high=20, size=(10))
print(arregloInt)

[ 9 14 12  1  8  7  7  8  7 15]


3. Crear un arreglo booleano

In [4]:
arregloBool = np.array([False, True, True, False, True, False])
print(arregloBool)

[False  True  True False  True False]


4. Extraer los items que sean divisibles en 3.

In [5]:
arregloDiv3 = arregloInt % 3 == 0
print("Booleanos que indican si son divisibles:")
print(arregloDiv3)
print()
print("Números del arreglo que son divisibles:")
print(arregloInt[arregloDiv3])

Booleanos que indican si son divisibles:
[ True False  True False False False False False False  True]

Números del arreglo que son divisibles:
[ 9 12 15]


5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [6]:
arregloTransf = arregloBool.reshape(3,2)
print(arregloTransf)

[[False  True]
 [ True False]
 [ True False]]


6. Obtén los items comunes entre dos arreglos

In [7]:
arregloA = np.array([1,2,3,4,5,6,7,8,9,10])
arregloB = np.array([2,4,6,8,10,12,14,16,18,20])
print("Elementos comunes:")
print(np.intersect1d(arregloA, arregloB))

Elementos comunes:
[ 2  4  6  8 10]


7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [8]:
valorPromedio = np.average(arregloInt)
print("Valor Promedio:", valorPromedio)
print()
numerosCercanos = np.where((arregloInt < valorPromedio +2) & (valorPromedio - 2 < arregloInt))

print("Los números cercanos al promedio son:", arregloInt[numerosCercanos])

Valor Promedio: 8.8

Los números cercanos al promedio son: [9 8 7 7 8 7]


8. Muestra solo 3 decimales en un vector.

In [9]:
arregloFloat = np.random.randn(10)
arregloLim = np.around(arregloFloat, decimals=3)
print(arregloLim)

[ 0.746 -0.617 -1.184 -1.404 -0.01   1.064  0.93  -0.348 -1.299 -0.824]


9. Crea una atriz de 3x3 con los valores del 0 a 8

In [10]:
matriz8 = np.arange(9).reshape(3,3)
print(matriz8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [11]:
ar = np.array([1,2,0,0,4])
indicesDif = np.where(ar > 0)
print(indicesDif)

(array([0, 1, 4], dtype=int64),)


11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [12]:
random30 = np.random.randint(0,50,30)
print("El arreglo es:", random30)
print("Su media es:", np.mean(random30))

El arreglo es: [39 24 35 34 33 14 11 47 29 42 13 32 41  9  3 15 18  0 43 41 20 45 43 19
 13 10 20 47  4 32]
Su media es: 25.866666666666667


12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [13]:
unos = np.ones((4,4))
print(unos)
print()
unos[1:-1,1:-1] = 0
print(unos)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False



14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

In [15]:
print(np.arange(1,4))

[1 2 3]


In [16]:
ceros = np.zeros((5,5))
print(ceros)
print()

ceros[np.arange(1,5), np.arange(0,4)] = [1, 2, 3, 4]
print(ceros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


15. Normaliza una matriz aleatoria de 5x5

In [43]:
mat5 = np.random.randint(low=0, high=10, size=(5,5))
print("Matriz:", mat5)
print()
det = np.linalg.det(mat5)
print("Determinante:", det)
print()
print(mat5*(1/det))

Matriz: [[3 5 2 6 7]
 [6 0 7 1 3]
 [1 7 8 5 3]
 [5 5 5 6 0]
 [8 1 7 3 4]]

Determinante: 102.00000000000004

[[0.02941176 0.04901961 0.01960784 0.05882353 0.06862745]
 [0.05882353 0.         0.06862745 0.00980392 0.02941176]
 [0.00980392 0.06862745 0.07843137 0.04901961 0.02941176]
 [0.04901961 0.04901961 0.04901961 0.05882353 0.        ]
 [0.07843137 0.00980392 0.06862745 0.02941176 0.03921569]]


In [38]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [17]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : 0.29.14
pytest           : 5.3.5
hypothesis       : 5.4.1
sphinx           : 2.3.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       :

Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [18]:
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index = labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


4. Regresa las primeras 3 filas del DataFrame

In [20]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [21]:
df.columns = ['Animal', 'Edad', 'Visitas', 'Prioridad']
print(df)

  Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no


6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [22]:
print(df[['Animal','Edad']])

  Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0


7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [23]:
visitasMayor3 = df['Visitas']>=3
print(df[visitasMayor3])

  Animal  Edad  Visitas Prioridad
b    cat   3.0        3       yes
d    dog   NaN        3       yes
f    cat   2.0        3        no


8. ¿Cuáles son las filas donde la edad es NaN?

In [24]:
edadNan = np.isnan(df['Edad'])
print(df[edadNan])

  Animal  Edad  Visitas Prioridad
d    dog   NaN        3       yes
h    cat   NaN        1       yes


9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [25]:
edadFiltro = df['Edad'].between(2,4)
print(df[edadFiltro])

  Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
f    cat   2.0        3        no
j    dog   3.0        1        no


10. ¿Cuál es el total de todas las visitas?

In [26]:
totalVisitas = df['Visitas'].sum()
print(totalVisitas)

19


12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [27]:
print(df.groupby(['Animal']).count())
print()
print(df['Animal'].value_counts())

        Edad  Visitas  Prioridad
Animal                          
cat        3        4          4
dog        3        4          4
snake      2        2          2

dog      4
cat      4
snake    2
Name: Animal, dtype: int64


13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [28]:
df.loc[df.Prioridad=='yes', 'Prioridad'] = True
df.loc[df.Prioridad=='no', 'Prioridad'] = False
print(df)

  Animal  Edad  Visitas Prioridad
a    cat   2.5        1      True
b    cat   3.0        3      True
c  snake   0.5        2     False
d    dog   NaN        3      True
e    dog   5.0        2     False
f    cat   2.0        3     False
g  snake   4.5        1     False
h    cat   NaN        1      True
i    dog   7.0        2     False
j    dog   3.0        1     False


14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [29]:
df.sort_values(by=['Edad', 'Visitas'], ascending=True)

Animal  Edad  Visitas Prioridad
c  snake   0.5        2     False
f    cat   2.0        3     False
a    cat   2.5        1      True
j    dog   3.0        1     False
b    cat   3.0        3      True
g  snake   4.5        1     False
e    dog   5.0        2     False
i    dog   7.0        2     False
h    cat   NaN        1      True
d    dog   NaN        3      True

15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [30]:
df.groupby(['Animal', 'Visitas']).mean()

Edad
Animal Visitas      
cat    1         2.5
       3         2.5
dog    1         3.0
       2         6.0
       3         NaN
snake  1         4.5
       2         0.5

# 3. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto